export const NATIONALITIES = [
  "Ethiopian",
  "Eritrean",
  "Djiboutian",
  "Kenyan",
  "Somali",
  "Sudanese",
  "South Sudanese",
  "Ugandan",
  "Tanzanian",
  "Rwandan",
  "Burundian",
  "Egyptian",
  "Nigerian",
  "Ghanaian",
  "South African",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Bangladeshi",
  "Belgian",
  "Brazilian",
  "British",
  "Bulgarian",
  "Cameroonian",
  "Canadian",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Congolese",
  "Cuban",
  "Czech",
  "Danish",
  "Dutch",
  "Emirati",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hungarian",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Japanese",
  "Jordanian",
  "Kuwaiti",
  "Lebanese",
  "Libyan",
  "Malaysian",
  "Mexican",
  "Moroccan",
  "Nepalese",
  "New Zealander",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palestinian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Saudi",
  "Senegalese",
  "Singaporean",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Swiss",
  "Syrian",
  "Thai",
  "Tunisian",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
  "Other",
] as const;

export const MARITAL_STATUS_OPTIONS = [
  "Single",
  "Married",
  "Not Married",
  "Divorced",
  "Widowed",
] as const;

export const GENDER_OPTIONS = [
  "Male",
  "Female",
  "Other",
  "Prefer not to say",
] as const;

export const EDUCATION_QUALIFICATIONS = [
  "Diploma in Hotel Management",
  "Diploma in Food & Beverage Management",
  "Diploma in Culinary Arts / Food Preparation",
  "Diploma in Front Office Operations",
  "Diploma in Housekeeping Management",
  "Diploma in Tourism & Hospitality Management",
  "Diploma in Accounting & Finance",
  "Diploma in Information Technology (IT)",
  "Diploma in Business Management",
  "Higher Diploma in Business Management",
  "Higher Diploma in Hotel Management",
  "Bachelor of Arts in Hospitality Management",
  "Bachelor of Arts in Hotel Management",
  "Bachelor of Arts in Tourism & Hospitality",
  "Bachelor of Arts in Business Administration",
  "Bachelor of Arts in Marketing Management",
  "Bachelor of Arts in Accounting",
  "Bachelor of Science in Food Science & Nutrition",
  "Bachelor's Degree",
  "Master of Business Administration (MBA)",
  "Master of Science in Hospitality Management",
  "Master's Degree",
  "TVET Level 4 / Advanced Certificate",
  "TVET Level 3 / Certificate",
  "TVET Level 2 / Certificate",
  "TVET Level 1 / Certificate",
  "Certificate in Food Preparation / Cooking",
  "Certificate in Barista & Beverage Service",
  "Certificate in Housekeeping Operations",
  "Certificate in Customer Service",
  "Grade 12 (High School Completion)",
  "Grade 10",
  "Secondary School Certificate",
  "Primary School Certificate",
  "Other",
] as const;

export const HOSPITALITY_SKILLS = [
  "POS & Property Management Systems (PMS)",
  "Product & Menu Knowledge (Barista skills, allergens)",
  "Food Safety, Hygiene & Sanitation",
  "Cash Handling & Transaction Processing",
  "Customer Service & Empathy",
  "Communication & Active Listening",
  "Conflict Resolution & De-escalation",
  "Teamwork & Cross-Department Coordination",
  "Time Management & Multitasking",
  "Attention to Detail",
  "Physical Stamina & Endurance",
  "Adaptability Under Pressure",
] as const;

